#! /bin/bash

measurements=$1
measurements_script=$2

# ruby 3.2.2
# asdf local ruby 3.2.2

RVERSION=$(ruby -v | cut -d ' ' -f 2)

ruby -v --jit
for iteration in {1..5}
do
  /usr/bin/time -o "time_"$RVERSION"jit_$iteration.txt" ruby --jit $measurements_script $measurements
done

ruby -v
for iteration in {1..5}
do
  /usr/bin/time -o "time_"$RVERSION"_$iteration.txt" ruby $measurements_script $measurements
done
